[faiss unreleased] Add get,set verbose for Index
Enet4/faiss-rs pull request #23
Opened 2021-05-04 15:15 UTC by ava57r

https://github.com/facebookresearch/faiss/pull/1790

2021-05-06 09:23 UTC, Enet4 commented
Thank you for your contributions to `faiss-rs` so far, @ava57r. Once these capabilities are given an actual release tag at the Faiss project, please let me know through these PRs, so that they may be reviewed. An eventual release of faiss-rs (0.10.0) is also soft blocked on an upcoming release, as it depends on the changes to CMake in order to build the C API.

2021-05-07 06:49 UTC, ava57r commented
I finished.
You can review it

2021-06-11 21:22 UTC, Enet4 requested changes
This does not compile with the `gpu` Cargo feature, but should be easy to fix.

2021-06-11 21:22 UTC, Enet4 commented on src/index/mod.rs
> +    fn set_verbose(&mut self, value: bool);
Please do not forget to add an implementation of these methods to `GpuIndexImpl` as well (see gpu.rs:225).

2021-06-12 09:39 UTC, Enet4 approved these changes

2021-06-12 09:39 UTC, merged