[faiss unreleased] Impl PreTransformIndex
Enet4/faiss-rs pull request #24
Opened 2021-05-13 10:24 UTC by ava57r

2021-05-31 15:22 UTC, ava57r commented
https://github.com/facebookresearch/faiss/pull/1816

and 
https://github.com/facebookresearch/faiss/pull/1869

merged

2021-06-12 10:16 UTC, Enet4 requested changes
While most of the constructs were well thought out, but this `PreTransform` can be exploited to perform memory unsafety.

- Values can outlive its native objects if they are not owned.
- `ConcurrentIndex` is implemented even if the native index does not.

More details and guidance in the comments below.

2021-06-12 10:16 UTC, Enet4 commented on src/index/pretransform.rs
> +    ) -> Result<Self> {
This enables the pre-transform index value to outlive both vector transform and underlying index, which is undefined behavior at least upon use. For example, this should not compile:

```rust
let mut pre_transform_index = {
    let vt = PCAMatrixImpl::new(8, D_OUT, 0f32, false)?;
    PreTransformIndexImpl::new_by_ref(&vt, &index)?
};
```

`PreTransformIndexImpl` will have to keep track of a lifetime for both of them. This is best done with a phantom value.

```rust
struct PreTransformIndexImpl<'a> {
    inner: *mut FaissIndexPreTransform,
    phantom: std::marker::PhantomData<&'a ()>,
}
```

Then over here we can require `lt` and `sub_index` to comply with the lifetime `'a`.
```suggestion
    pub fn new_by_ref<LT: NativeVectorTransform, I: NativeIndex>(
        lt: &'a LT,
        sub_index: &'a I,
    ) -> Result<Self> {
```

For an owned pre-transform index, I imagine that returning a `PreTransformIndexImpl<'static>` would work.

It might also be worth changing this constructor to take *mutable references*, because otherwise nothing stops them from being used separately in other parts of the program, even concurrent use, which may be incompatible with the native index implementation.

2021-06-12 10:16 UTC, Enet4 commented on src/index/pretransform.rs
> +impl ConcurrentIndex for PreTransformIndexImpl {
This one should only be implemented if the sub-index is also a concurrent index. We can keep track of the underlying index type `I` through phantom data. The complete version would be:

```rust
struct PreTransformIndexImpl<'a, I> {
    inner: *mut FaissIndexPreTransform,
    phantom: std::marker::PhantomData<(&'a (), I)>,
}
```

Then `into_pre_transform(self)` would return a `PreTransformIndexImpl<'static, Self>`.

2021-06-12 11:47 UTC, ava57r commented
Maybe we should not use the option when `own_fields = = false`?

2021-06-13 11:40 UTC, Enet4 commented
> Maybe we should not use the option when `own_fields = = false`?

I mean, I suppose part of the problem would no longer apply if we require all indexes to be owned (and so `own_fields` would never be `false`), but adding a few type/lifetime parameters should do the trick here.

2021-06-13 17:43 UTC, ava57r commented
I won't complicate the impl. I like the transfer of ownership.

2021-06-13 18:43 UTC, ava57r commented
I suggest starting with the ownership of indexes, quantizers. In the future, it will become clear whether to use `own_fields = = false`

2021-06-21 18:24 UTC, Enet4 approved these changes
Thank you.

2021-06-21 18:24 UTC, merged