[faiss unreleased] Impl RefineFlatIndex
Enet4/faiss-rs pull request #25
Opened 2021-05-13 13:14 UTC by ava57r

fixes #18 

https://github.com/facebookresearch/faiss/pull/1821

2021-05-27 17:04 UTC, Enet4 commented
We'll hopefully be able to review this PR and the other ones once facebookresearch/faiss#1915 is resolved.

2021-05-31 06:02 UTC, ava57r commented
faiss release tagged [v1.7.1](https://github.com/facebookresearch/faiss/releases/tag/v1.7.1)

2021-06-12 10:22 UTC, Enet4 requested changes
This one appears to have the same issues reported in #24. Please look into the pre-transform index and apply the same pattern of resolution here.

2021-06-12 10:22 UTC, Enet4 commented on src/index/refine_flat.rs
> +}
We will need to keep track of the underlying index implementation and lifetime, and make the necessary changes accordingly.
```suggestion
pub struct RefineFlatIndexImpl<'a, I> {
    inner: *mut FaissIndexRefineFlat,
    phantom: std::marker::PhantomData<&'a I>,
}
```

2021-06-21 18:58 UTC, Enet4 approved these changes
Looks good now, thank you!

2021-06-21 18:58 UTC, merged