Support static link as a feature
Enet4/faiss-rs pull request #67
Opened 2023-04-26 05:59 UTC by SkyFan2002

After enabling the `static` feature, users do not need to download and build faiss, so it can be used out of the box.

2023-04-28 07:54 UTC, Enet4 requested changes
Hello! Thank you for this very interesting contribution, It may indeed help some users take advantage of the library.

I have raised some concerns in the comments below, but once they're sorted out we can continue with the review and testing.

2023-04-28 07:54 UTC, Enet4 commented on .gitmodules
> +	url = https://github.com/SkyFan2002/faiss.git
If there is something simple that needs to exist at the faiss repo, let me know so that it can be added to my fork.

2023-04-28 07:54 UTC, Enet4 commented on faiss-sys/Cargo.toml
> +cmake = "0.1.50"
Can this be made an optional dependency (only required by `static`)?

2023-04-28 07:54 UTC, Enet4 commented on faiss-sys/c_api.h
> +// Auto-generated, do not edit!
This one was probably added by mistake. Since it it generated whenever it is needed, it does not have to be checked out into the repository.

2023-04-28 07:54 UTC, Enet4 commented on faiss-sys/gen_bindings.sh
> +bindgen_opt='--opaque-type FILE'
Removing the whitelist has made bindgen add lots of symbols which are not truly part of the library. We need to bring these filters back, or use a separate generated copy during static linking.

2023-04-28 07:54 UTC, Enet4 commented on src/index/io.rs
> +pub use faiss_sys::seralize_index as serialize_index;
This re-export does not seem justified. The `faiss` crate should provide a memory safe, high level abstraction over the low level API. This too can be done, although it may be best done in a separate pull request.

2023-04-28 08:28 UTC, SkyFan2002 commented
By the way, it seems that due to the update of bindgen, the `gen_bindings.sh` is no longer valid
```shell
$ ./gen_bindings.sh 
fatal: destination path 'faiss' already exists and is not an empty directory.
ls: cannot access 'faiss/c_api/impl/*_c.h': No such file or directory
ls: cannot access 'faiss/c_api/utils/*_c.h': No such file or directory
bindgen --rust-target 1.33 --size_t-is-usize --whitelist-function faiss_.* --whitelist-type idx_t|Faiss.* --opaque-type FILE c_api.h -o src/bindings.rs
error: unexpected argument '--size_t-is-usize' found

  tip: a similar argument exists: '--no-size_t-is-usize'

Usage: bindgen [FLAGS] [OPTIONS] [HEADER] -- [CLANG_ARGS]...

For more information, try '--help'.
bindgen --rust-target 1.33 --size_t-is-usize --whitelist-function faiss_.* --whitelist-type idx_t|Faiss.* --opaque-type FILE c_api.h -o src/bindings_gpu.rs -- -Ifaiss/c_api -I/opt/cuda/include
error: unexpected argument '--size_t-is-usize' found

  tip: a similar argument exists: '--no-size_t-is-usize'

Usage: bindgen [FLAGS] [OPTIONS] [HEADER] -- [CLANG_ARGS]...

For more information, try '--help'.
$ bindgen --version
bindgen 0.65.1
```

2023-04-28 08:37 UTC, Enet4 commented
> By the way, it seems that due to the update of bindgen, the `gen_bindings.sh` is no longer valid

Hmm, maybe I should have recorded which version of rust-bindgen I was using.
It appears that the behavior _`size_t` is `usize`_ has become the default, so the flag `--size_t-is-usize` can be removed.
The [rust-bindgen changelog](https://github.com/rust-lang/rust-bindgen/blob/main/CHANGELOG.md) might help track down the latest changes and know what to update here.

The other errors may have to do with `faiss` now existing as a git submodule.

2023-04-28 08:41 UTC, SkyFan2002 commented
> ```shell
> --whitelist-function
> ```

In fact,`--whitelist-function` is invalid, eithier.
```sh
error: unexpected argument '--whitelist-type' found

  tip: a similar argument exists: '--allowlist-type'
```

2023-04-30 02:20 UTC, SkyFan2002 commented
What can I do to have this PR continued? I apologize for may have been impolite before.

2023-04-30 10:56 UTC, Enet4 requested changes
@SkyFan2002 No harm taken at all! I am just trying to help you resolve some of the issues here, as I may not be able to fill in all the gaps. It may also take some time to review and provide feedback, as I cannot commit to a prompt reply for this particular project.

---

The two major issues I could find right now are:

- The faiss-sys/faiss submodule should check out branch `c_api_head` instead of the default branch.
- `gen_bindings.sh` will indeed need to be modified so that it does not try to clone and clean up faiss if the git submodule has already been checked out. Another easy way around this is to use a different destination name, although in this case we would be making a redundant version. I added a suggested change for this.
- Other minor tweaks in the code follow.
- Updating `gen_bindings.sh` to support the latest version of bindgen is secondary, but would be OK to introduce here as well.

2023-04-30 10:56 UTC, Enet4 commented on .gitmodules
> +	url = https://github.com/Enet4/faiss.git
The submodule should point to branch `c_api_head`.
```suggestion
	url = https://github.com/Enet4/faiss.git
	branch = c_api_head
```

2023-04-30 10:56 UTC, Enet4 commented on faiss-sys/build.rs
> +fn link_cxx() {
```suggestion
#[cfg(feature = "static")]
fn link_cxx() {
```

2023-04-30 11:27 UTC, SkyFan2002 commented
Hi, thanks for your help. I have fixed the repeated clone issue. As for the bindgen version, `--size_t-is-usize` can be deleted directly, but the `--whitelist-function` and `--whitelist-type` has been deprecated, and I don't know if there is an API with similar semantics.
Do you have any idea about this?Or I am glad to try to solve this in anothr PR.

2023-06-01 08:35 UTC, web3creator commented
@SkyFan2002 Why is this PR closed?I hope to add support for static libraries, but I don't know c language

2023-06-02 09:23 UTC, Enet4 commented
It seems to have compiled seamlessly on my Linux machine. But I wonder, how can one specify more details about the compilation and linking of Faiss without changing the build script? In particular, it should be possible to define some of the options found [here](https://github.com/facebookresearch/faiss/blob/main/INSTALL.md#step-1-invoking-cmake), including which BLAS implementation to use, where to find CUDA in case of GPU support, and whether to use the `avx2` optimization level.
If there is no way to define these options from outside (maybe specially written environment variables?), we should open a way to do this ourselves at faiss-sys, using environment variables and/or Cargo features.

2023-08-23 14:49 UTC, jondot commented
@Enet4 I've been playing around (actually pulling hair!) with building an abstraction that depends on `faiss-rs`, and my impression is that this PR offers a better starting point for dynamic linking _and a reasonable static linking experience_. Reasonable being that we can assume that the static linking build -- as it is now in this PR -- does not support advanced options.

All in all, I'm getting a smoother experience with the static build. I've locally updated to 1.7.x with no issues (faiss master), and build went smoothly with a small tweak.

Any thoughts on merging this PR for a *starting point* for static linking, having that it gives the existing dynamic linking experience an equivalent value?

2023-08-23 16:41 UTC, SkyFan2002 commented
@Enet4 . Let's merge. I'm willing to help if advanced options are needed by someone in the future.

2023-08-23 17:30 UTC, merged